version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chawkbazar-backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - JWT_SECRET=${JWT_SECRET:-supersecretjwtkey}
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=http://localhost:3000,http://localhost:3001
    restart: unless-stopped
    networks:
      - chawkbazar-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  shop:
    build:
      context: .
      dockerfile: Dockerfile.shop
    container_name: chawkbazar-shop
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_REST_API_ENDPOINT=http://backend:8000
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-chawkbazar-shop-secret}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - chawkbazar-network

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: chawkbazar-admin
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_REST_API_ENDPOINT=http://backend:8000
      - NEXT_PUBLIC_SHOP_URL=http://localhost:3000
      - NEXT_PUBLIC_SITE_URL=http://localhost:3001
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-chawkbazar-admin-secret}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - chawkbazar-network

networks:
  chawkbazar-network:
    driver: bridge

volumes:
  backend-uploads:
