version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: chawkbazar_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chawkbazar
      MYSQL_USER: chawkbazar_user
      MYSQL_PASSWORD: chawkbazar_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - chawkbazar_network
    command: --default-authentication-plugin=mysql_native_password

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: chawkbazar_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chawkbazar_network
    command: redis-server --appendonly yes

  # Laravel Backend API (Using existing Dockerfile)
  backend:
    build:
      context: ./chawkbazar-api
      dockerfile: Dockerfile
    container_name: chawkbazar_backend
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your-app-key-here
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=chawkbazar
      - DB_USERNAME=chawkbazar_user
      - DB_PASSWORD=chawkbazar_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    volumes:
      - ./chawkbazar-api:/var/www/html
      - backend_storage:/var/www/html/storage
      - backend_bootstrap_cache:/var/www/html/bootstrap/cache
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    networks:
      - chawkbazar_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  backend_storage:
    driver: local
  backend_bootstrap_cache:
    driver: local

networks:
  chawkbazar_network:
    driver: bridge
